name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - name: Build
        run: |
          pnpm build
          tar -czf bangumi-website.tar.gz  -C ./packages/website/dist .
          openssl dgst -sha256 bangumi-website.tar.gz > bangumi-website.tar.gz.sha256

      - name: Get Tag Name
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Upload Github Release
        run: gh release create "$TAG" bangumi-website.tar.gz bangumi-website.tar.gz.sha256 --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload website build artifact
        uses: actions/upload-artifact@v3
        with:
          name: sites
          path: packages/website/dist

  milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - name: Update github milestone
        run: npx tsx .github/scripts/milestone.mts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
